[workspace]
resolver = "3"

members = [
    "zenith-sandbox",

    "zenith",
    "zenith-core",
    "zenith-rhi",
    "zenith-rendergraph",
    "zenith-rhi-derive",
    "zenith-renderer",
    "zenith-asset",
]

[workspace.dependencies]
ash = { version = "0.38.0", features = ["std", "debug", "loaded"] }
winit = "0.30.11"
log = "0.4"
bytemuck = { version = "1.23", features = ["derive"] }
glam = "0.30"
anyhow = "1.0.98"
derive_more = { version = "2.0.1", features = ["full"] }
derive_builder = "0.20.2"
parking_lot = "0.12"
paste = "1.0.15"
profiling = { version = "1.0.17", features = ["profile-with-puffin"] }
