[workspace]
resolver = "3"
exclude = ["vendor/ash", "vendor/ash-window", "vendor/vk-mem"]

members = [
    "zenith-sandbox",

    "zenith",
    "zenith-core",
    "zenith-rhi",
    "zenith-rendergraph",
    "zenith-renderer",
    "zenith-asset",
    "zenith-ui",
]

[workspace.dependencies]
ash = { version = "0.38.0", features = ["std", "debug", "loaded"] }
winit = "0.30.11"
egui = { version = "0.36.2", features = ["bytemuck"] }
egui-winit = { version = "0.36.2", default-features = false, features = ["clipboard", "links"] }
log = "0.4"
bytemuck = { version = "1.23", features = ["derive"] }
glam = "0.32.0"
anyhow = "1.0.98"
derive_more = { version = "2.0.1", features = ["add", "add_assign", "deref", "deref_mut", "from", "into", "mul", "mul_assign", "not"] }
parking_lot = "0.12"
profiling = "1.0.18"
puffin_egui = { git = "https://github.com/EmbarkStudios/puffin", rev = "4bdd85760c895623b08f236c23cf54bbaaafd91b" }
bitflags = "2"

[patch.crates-io]
ash = { path = "vendor/ash" }
ash-window = { path = "vendor/ash-window" }
vk-mem = { path = "vendor/vk-mem" }
puffin = { git = "https://github.com/EmbarkStudios/puffin", rev = "4bdd85760c895623b08f236c23cf54bbaaafd91b" }

[profile.dev.package.zstd-sys]
opt-level = 3

[profile.dev.package.epaint]
opt-level = 3
