[workspace]
resolver = "3"
exclude = ["vendor/ash", "vendor/ash-window", "vendor/vk-mem"]

members = [
    "zenith-sandbox",

    "zenith",
    "zenith-core",
    "zenith-rhi",
    "zenith-rendergraph",
    "zenith-renderer",
    "zenith-asset",
]

[workspace.dependencies]
ash = { version = "0.38.0", features = ["std", "debug", "loaded"] }
winit = "0.30.11"
log = "0.4"
bytemuck = { version = "1.23", features = ["derive"] }
glam = "0.32.0"
anyhow = "1.0.98"
derive_more = { version = "2.0.1", features = ["add", "add_assign", "deref", "deref_mut", "from", "into", "mul", "mul_assign", "not"] }
parking_lot = "0.12"
profiling = "1.0.17"
bitflags = "2"

[patch.crates-io]
ash = { path = "vendor/ash" }
ash-window = { path = "vendor/ash-window" }
vk-mem = { path = "vendor/vk-mem" }
