[package]
name = "zenith-ui"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow.workspace = true
bytemuck.workspace = true
egui.workspace = true
egui-winit.workspace = true
winit.workspace = true
zenith-rhi = { path = "../zenith-rhi" }
zenith-rendergraph = { path = "../zenith-rendergraph" }

[dev-dependencies]
zenith-core = { path = "../zenith-core" }
