[package]
name = "zenith"
version = "0.1.0"
edition = "2021"

[dependencies]
winit = { workspace = true }
anyhow = { workspace = true }
profiling.workspace = true


zenith-core = { path = "../zenith-core" }
zenith-asset = { path = "../zenith-asset" }
zenith-rhi = { path = "../zenith-rhi" }
zenith-renderer = { path = "../zenith-renderer" }
zenith-rendergraph = { path = "../zenith-rendergraph" }

[features]
cpu-profiling = ["zenith-core/cpu-profiling"]
extra-image-formats = ["zenith-asset/extra-image-formats"]
