[package]
name = "zenith-sandbox"
version = "0.1.0"
edition = "2021"
description = "Sandbox application for Zenith engine"
license = "MIT"

[dependencies]
anyhow.workspace = true

zenith = { path = "../zenith", features = ["ui"] }

[dev-dependencies]
winit.workspace = true
glam.workspace = true

[features]
cpu-profiling = ["zenith/cpu-profiling"]
extra-image-formats = ["zenith/extra-image-formats"]
