[package]
name = "zenith-core"
version = "0.1.0"
edition = "2021"
description = "Core module for Zenith"
license = "MIT"

[dependencies]
anyhow = { workspace = true }
log = { workspace = true }
glam = { workspace = true }
derive_more = { workspace = true }
winit = { workspace = true }
profiling = { workspace = true }

memmap2 = "0.9"
env_logger = "0.11"
smallvec = "1.15"
hashbrown = { version = "0.15.4", default-features = false, features = ["default-hasher", "inline-more"] }
foldhash = "0.1.5"
clap = { version = "4.5", default-features = false, features = ["std", "derive", "help", "usage", "error-context"] }

[features]
cpu-profiling = ["profiling/profile-with-puffin"]
