[package]
name = "zenith-asset"
version = "0.1.0"
edition = "2024"

[dependencies]
bytemuck = { workspace = true }
anyhow = { workspace = true }
parking_lot = { workspace = true }
glam = { workspace = true }
profiling = { workspace = true }
ash = { workspace = true }

rayon = "1.10"
ispc-texcomp = "0.1.20"
zstd = { version = "0.13.3", default-features = false }
half = "2.7.1"
gltf = { version = "1.4", default-features = false, features = ["import", "utils"] }
image = { version = "0.25", default-features = false, features = ["png", "jpeg", "hdr", "bmp", "tga", "tiff", "webp"] }
bincode = { version = "2.0.1", default-features = false, features = ["std", "serde"] }
serde = { version = "1.0", features = ["derive"] }

zenith-core = { path = "../zenith-core" }

[features]
extra-image-formats = ["image/default-formats"]
