[package]
name = "zenith-renderer"
version = "0.1.0"
edition = "2021"

[dependencies]
bytemuck.workspace  = true
anyhow.workspace = true
glam.workspace = true
enumflags2 = { workspace = true }

zenith-core = { path = "../zenith-core" }
zenith-rhi = { path = "../zenith-rhi" }
zenith-rendergraph = { path = "../zenith-rendergraph" }
zenith-asset = { path = "../zenith-asset" }
